import { useEffect, useState } from "react";
import { Bot, Send, X, Loader2 } from "lucide-react";
import { supabase } from "../lib/supabase";
export function AIAssistant({projectId,sceneId,onClose}:{projectId?:string;sceneId?:string;onClose:()=>void}){
 const[messages,setMessages]=useState<{role:string;content:string}[]>([]),[input,setInput]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!supabase)return;(async()=>{const{data}=await supabase.from("omniforge_assistant_messages").select("role,content").eq("project_id",projectId||"00000000-0000-0000-0000-000000000000").order("created_at",{ascending:true}).limit(40);setMessages(data||[])})()},[projectId]);
 async function send(){const text=input.trim();if(!text||!supabase||loading)return;setInput("");setLoading(true);try{const u=(await supabase.auth.getUser()).data.user;if(!u)throw new Error("Sign in required.");await supabase.from("omniforge_assistant_messages").insert({user_id:u.id,project_id:projectId||null,scene_id:sceneId||null,role:"user",content:text});setMessages(m=>[...m,{role:"user",content:text}]);const reply=buildReply(text);await supabase.from("omniforge_assistant_messages").insert({user_id:u.id,project_id:projectId||null,scene_id:sceneId||null,role:"assistant",content:reply});setMessages(m=>[...m,{role:"assistant",content:reply}]);}catch(e:any){setMessages(m=>[...m,{role:"assistant",content:e?.message||"Assistant request failed."}])}finally{setLoading(false)}}
 function buildReply(t:string){const x=t.toLowerCase();if(x.includes("character"))return"Use Character Forge to generate a character, then select the resulting asset for rigging and animation. I can keep this workflow tied to the current project.";if(x.includes("scene"))return"Your current Studio scene can be saved to the selected project. Use Save Scene after composing the viewport.";if(x.includes("texture")||x.includes("material"))return"Open Materials to generate or retexture an existing 3D asset. Provider credentials stay server-side.";if(x.includes("asset"))return"Your Asset Library stores uploaded assets privately and tracks generated assets in Supabase.";return"I can guide the current OMNIFORGE workflow. Try: generate a character, build a scene, texture an asset, or manage project assets."}
 return <aside className="ai-assistant"><header><div><Bot size={17}/> OMNIFORGE Assistant</div><button onClick={onClose}><X size={16}/></button></header><div className="ai-messages">{messages.length?messages.map((m,i)=><div key={i} className={"ai-message "+m.role}>{m.content}</div>):<div className="ai-empty">Ask about your current project, scene, assets, characters, materials, or workflow.</div>}</div><div className="ai-input"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder="Ask OMNIFORGE..." maxLength={1000}/><button onClick={send} disabled={loading}>{loading?<Loader2 className="spin" size={15}/>:<Send size={15}/>}</button></div></aside>
}