import { useEffect, useRef, useState } from "react";
import { Box, FileUp, Loader2, Trash2, ExternalLink, RefreshCw } from "lucide-react";
import { supabase } from "../lib/supabase";

type Asset={id:string;name:string;asset_type:string;status:string;source_url:string|null;storage_path:string|null;created_at:string;metadata:any};

export function AssetLibrary({onOpenStudio}:{onOpenStudio:(url?:string)=>void}) {
 const [assets,setAssets]=useState<Asset[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[uploading,setUploading]=useState(false);
 const input=useRef<HTMLInputElement>(null);
 async function load(){if(!supabase)return;setLoading(true);setError("");const {data,error}=await supabase.from("omniforge_assets").select("*").order("created_at",{ascending:false});if(error)setError(error.message);else setAssets((data||[]) as Asset[]);setLoading(false);}
 useEffect(()=>{load()},[]);
 async function upload(file:File){if(!supabase)return;setUploading(true);setError("");try{const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("You must be signed in.");const path=user.id+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const {error:e}=await supabase.storage.from("omniforge-assets").upload(path,file,{contentType:file.type||"application/octet-stream",upsert:false});if(e)throw e;const {data:row,error:re}=await supabase.from("omniforge_assets").insert({user_id:user.id,name:file.name,asset_type:file.type.includes("gltf")||file.name.match(/\.(glb|gltf|obj|fbx)$/i)?"3D Model":"File",status:"ready",storage_path:path,metadata:{mime_type:file.type,size:file.size}}).select().single();if(re)throw re;setAssets(a=>[row as Asset,...a]);}catch(e:any){setError(e?.message||"Upload failed.")}finally{setUploading(false)}}
 async function remove(a:Asset){if(!supabase)return;setError("");try{if(a.storage_path){const {error:e}=await supabase.storage.from("omniforge-assets").remove([a.storage_path]);if(e)throw e;}const {error:e}=await supabase.from("omniforge_assets").delete().eq("id",a.id);if(e)throw e;setAssets(x=>x.filter(i=>i.id!==a.id));}catch(e:any){setError(e?.message||"Delete failed.")}}
 async function open(a:Asset){if(a.source_url){onOpenStudio(a.source_url);return;}if(a.storage_path&&supabase){const {data,error}=await supabase.storage.from("omniforge-assets").createSignedUrl(a.storage_path,3600);if(error)setError(error.message);else if(data?.signedUrl)onOpenStudio(data.signedUrl);}}
 return <div className="asset-library"><header className="library-header"><div><div className="eyebrow">ASSET LIBRARY</div><h1>Your digital assets.</h1><p>Generated and uploaded files are stored securely in your private OMNIFORGE bucket.</p></div><div className="library-actions"><button className="secondary" onClick={load}><RefreshCw size={15}/>Refresh</button><button className="primary" onClick={()=>input.current?.click()} disabled={uploading}>{uploading?<Loader2 className="spin" size={16}/>:<FileUp size={16}/>}Upload Asset</button><input ref={input} hidden type="file" accept=".glb,.gltf,.obj,.fbx,.png,.jpg,.jpeg,.webp" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=""}}/></div></header>{error&&<div className="workspace-error">{error}</div>}{loading?<div className="empty-workspace">Loading assets…</div>:assets.length===0?<div className="empty-workspace"><Box size={25}/><h3>No assets yet</h3><p>Upload a 3D file or generate one with AI.</p></div>:<div className="asset-grid">{assets.map(a=><article className="asset-card" key={a.id}><div className="asset-thumb">{a.metadata?.thumbnail_url?<img src={a.metadata.thumbnail_url} alt="" />:<Box size={30}/>}</div><div className="asset-meta"><span>{a.asset_type}</span><small>{a.status}</small></div><h3>{a.name}</h3><div className="asset-actions">{(a.source_url||a.storage_path)&&<button className="secondary" onClick={()=>open(a)}><ExternalLink size={14}/>Open in Studio</button>}<button className="icon-button danger" onClick={()=>remove(a)} title="Delete asset"><Trash2 size={14}/></button></div></article>)}</div>}</div>
}