import { useEffect,useState } from "react";
import { KeyRound, Copy, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { supabase } from "../lib/supabase";
async function hash(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("")}
function makeKey(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return "of_live_"+Array.from(bytes).map(x=>x.toString(16).padStart(2,"0")).join("")}
export function DeveloperPlatform(){
 const[keys,setKeys]=useState<any[]>([]),[name,setName]=useState("Production key"),[newKey,setNewKey]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){if(!supabase)return;const{data,error}=await supabase.from("omniforge_api_keys").select("id,name,key_prefix,last_used_at,revoked_at,created_at").order("created_at",{ascending:false});if(error)setError(error.message);else setKeys(data||[])}
 useEffect(()=>{load()},[]);
 async function create(){if(!supabase)return;setBusy(true);setError("");try{const raw=makeKey(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in required.");const{error}=await supabase.from("omniforge_api_keys").insert({user_id:user.id,name:name.trim()||"API key",key_prefix:raw.slice(0,16),key_hash:await hash(raw)});if(error)throw error;setNewKey(raw);await load()}catch(e:any){setError(e.message||"Could not create key.")}finally{setBusy(false)}}
 async function revoke(id:string){if(!supabase)return;const{error}=await supabase.from("omniforge_api_keys").update({revoked_at:new Date().toISOString()}).eq("id",id);if(error)setError(error.message);else load()}
 return <div className="developer-page"><header className="library-header"><div><div className="eyebrow">DEVELOPER PLATFORM</div><h1>Build with OMNIFORGE.</h1><p>Create API credentials for server-side integrations. Keys are shown once and stored only as hashes.</p></div><button className="secondary" onClick={load}><RefreshCw size={15}/>Refresh</button></header>{error&&<div className="workspace-error">{error}</div>}<section className="developer-card"><div className="developer-card-head"><div><h2>API Keys</h2><p>Use <code>x-api-key</code> from your backend integration.</p></div><div className="developer-create"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Key name"/><button className="primary" onClick={create} disabled={busy}><Plus size={15}/>Create Key</button></div></div>{newKey&&<div className="new-key"><ShieldCheck size={17}/><div><strong>Copy this key now</strong><code>{newKey}</code></div><button className="secondary" onClick={()=>navigator.clipboard.writeText(newKey)}><Copy size={14}/>Copy</button></div>}<div className="api-key-list">{keys.map(k=><div className="api-key-row" key={k.id}><KeyRound size={16}/><div><strong>{k.name}</strong><small>{k.key_prefix}•••• · {k.revoked_at?"Revoked":"Active"}</small></div>{!k.revoked_at&&<button className="icon-button danger" onClick={()=>revoke(k.id)} title="Revoke key"><Trash2 size={14}/></button>}</div>)}</div></section><section className="developer-card"><h2>API base</h2><code>https://eaxfkkuzdlguybhbdapp.supabase.co/functions/v1/omniforge-api</code><p>Current endpoint exposes authenticated asset/project metadata and export URLs for authorized API-key requests.</p></section></div>
}